# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoDip
                                 A QGIS plugin
 Automatiza el ploteo de medidas estructurales (Dip y Dip-Direction) desde Excel/CSV o ploteo manual.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-16
        copyright            : (C) 2026 by Pablo Guzman H
        email                : pabloguzmanherr@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoDip class from file GeoDip.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_dip import GeoDip
    return GeoDip(iface)
